apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
-  ../../base/application



namePrefix: production-

patches:
- path: deployment-patch.yaml
- path: ingress.yaml

