apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
-  ../../base/application



namePrefix: development-

patches:
- path: deployment-patch.yaml
- path: ingress.yaml

