version: "3"

services:
  jenkins:
    image: jenkins/jenkins:2.452.3-lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins-casc.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins-casc.yaml:/var/jenkins_home/casc_configs/jenkins-casc.yaml
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./install-plugins.sh:/usr/local/bin/install-plugins.sh
      - ./job-pipelines:/var/jenkins_home/workspace/JOB-DSL/job-pipelines
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bin/bash", "/usr/local/bin/install-plugins.sh"]
