name: Terraform Apply for ECS

on:
  push:
    branches:
      - testing
      - develop
      - main
    paths:
      - 'terraform/ecs-ec2-backend/**'
      - 'terraform/ecs-ec2-frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - terraform/ecs-ec2-backend
          - terraform/ecs-ec2-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: CD For ECS
        run: echo "Hello World from GitHub Actions!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::xxxx:role/GitHubActionsOIDCRole"
          aws-region: ca-central-1

      - name: Check if directory changed
        id: check_changes
        run: |
          echo "changed=false" >> $GITHUB_ENV
          # Fetch full history to ensure ~1 exists
          git fetch origin ${{ github.ref }} --depth=2
          if git diff --name-only HEAD~1 HEAD | grep -q "^${{ matrix.directory }}/"; then
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        if: env.changed == 'true'
        run: terraform -chdir=${{ matrix.directory }} init -input=false

      - name: Terraform Plan
        if: env.changed == 'true'
        run: terraform -chdir=${{ matrix.directory }} plan -out=tfplan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && env.changed == 'true'
        run: terraform -chdir=${{ matrix.directory }} apply -input=false -auto-approve tfplan
