apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
-  ../../base/application



namePrefix: staging-

patches:
- path: deployment-patch.yaml
- path: ingress.yaml

